version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mydb_test
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: mybackend_test
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: test
      DB_HOST: db
      DB_NAME: test
      DB_USER: root
      DB_PASS: password
    depends_on:
      db:
        condition: service_healthy